// export const ME = '/me'
// export const LOGIN = '/login'
export const REGISTER = '/register'
// export const CHANGE_PASSWORD = '/change_password'
// export const FORGOT_PASSWORD = '/forgot_password'
