// export const ME = '/me'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const ACTIVATE = '/activation'
// export const CHANGE_PASSWORD = '/change_password'
export const FORGET_PASSWORD = '/forgetpassword'
