export const REGISTER_USER = 'AUTH_REGISTER_USER'
export const ACTIVATE_USER = 'AUTH_ACTIVATE_USER'
export const LOGIN = 'AUTH_LOGIN'

export const ERROR = 'AUTH_ERROR'
export const CLEAR_ERROR = 'AUTH_CLEAR_ERROR'
